export const userData = [
    {
      name: 'Jan',
      "Active Users": 4000,
      pv: 2400,
      amt: 2400,
    },
    {
      name: 'Feb',
      "Active Users": 3000,
      pv: 1398,
      amt: 2210,
    },
    {
      name: 'Mar',
      "Active Users": 4600,
      pv: 9800,
      amt: 2290,
    },
    {
      name: 'Apr',
      "Active Users": 3500,
      pv: 3908,
      amt: 2000,
    },
    {
      name: 'May',
      "Active Users": 2000,
      pv: 4800,
      amt: 2181,
    },
    {
      name: 'Jun',
      "Active Users": 500,
      pv: 3800,
      amt: 2500,
    },
    {
      name: 'Jul',
      "Active Users": 5000,
      pv: 4300,
      amt: 2100,
    },
  ];

  export const userRows = [
    { 
        id: 1, 
        username: 'Red The Hero', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 2, 
        username: 'Chuck', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 3, 
        username: 'Bomb', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 4, 
        username: 'Zeta', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 5, 
        username: 'Silver', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 6, 
        username: 'Mighty Eagle', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 7, 
        username: 'Chef Pig Phillip', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 8, 
        username: 'Early Bird', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 9, 
        username: 'Willow', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 10, 
        username: 'Earl Pig', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
    { 
        id: 11, 
        username: 'Hal', 
        avatar: 'https://vignette3.wikia.nocookie.net/parody/images/9/9d/Red_angry_birds_movie.jpg/revision/latest?cb=20150618025632',
        email: "red@angrybird.com",
        status: "active",
        transaction: "$98,000",
    },
  ];